name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install eslint and dependencies
      run: |
        npm install glob;
        npm install --only=dev typescript eslint jsonlint-mod @typescript-eslint/parser @typescript-eslint/eslint-plugin mkdirp@latest;
    - name: Run eslint
      run: npx eslint --ext .ts,.vue pages --quiet